language: minimal
dist: xenial
sudo: false
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - "1.11.x"
  - tip
env:
  # Install dependencies based on the glide.lock
  #- DEPS=''
  # Upgrade to the latest dependencies
  #- DEPS='-update'
  - GO111MODULE=on
matrix:
  fast_finish: true
  allow_failures:
  # Allow Go 1.6, and tip to fail, as well as whenever we use upgraded dependencies
  - go: 1.6
  - go: tip
  - env: DEPS='-update'
before_install:
- sudo apt-get install -y build-essential git python-pip sqlite3
- sudo apt-get install -y curl
- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo pip install requests
- sudo npm install -g gulp
- sudo npm install -g gulp-cli
- curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz --output /tmp/go1.12.1.linux-amd64.tar.gz
- sudo tar -C /usr/local -zxf /tmp/go1.12.1.linux-amd64.tar.gz
  # Fix pathing for forks
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - mkdir -p $HOME/gopath/src/github.com/akamai/AkamaiOPEN-edgegrid-golang
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/akamai/AkamaiOPEN-edgegrid-golang/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/akamai/AkamaiOPEN-edgegrid-golang
  - cd $HOME/gopath/src/github.com/akamai/AkamaiOPEN-edgegrid-golang
script:
  - export GOROOT=/usr/local/go
  - export GOPATH=$HOME/go
  - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  - go version
  - which go
  - ls -d */ | grep -vE '(examples|testdata|vendor)' | xargs -I {package} go test -v ./{package}
notifications:
  slack:
    secure: sf5CrgPZ2UjTmGFg1hbSdEB3GXyBybeoZQDOI/pk1ywId4mjN1HgAFooDaZx9Qn+orhdQny3jMcdx1qyLe9YtV7WhIRGRQWgJiZ7H+6YRCWYNnSopsSDJ91Q/PaQrgsPSIHL+vfSkyW9iDXrT09SK0IOlWHTrrYMcJiiOCkx2QZgIBMASXWzCRFMSxfqDBuZ8FuNMhcYTIEz4xBLO7seAl9+FvQTzpSXXyEwoKeZjLx2J2+9J1onx9ccnb5ioPeICRuiIKlSvu7VfFkDgc8k8luoktKSG+ZRpwcdae8VoQCzyt7OPzI1kSoZZw20gp2oYQcRkwpLBM007JkW2+KQraF5tZ9Ok8C1vG97lsByhd23r022joyTGpD+TZqWfXUX7K461GJJpohWoFlHshOaAwNj37XWKD8REpb0Qj7vABIfH+gXQhlJHBRCfKMRf12ILzU2yUbbQftwcPkcivNHGknEAkHIjWKk5lDH9uC2is5nWJHDCt/h/xa/AfvNbt28Kol+8yexRypnmorTzG9CBHq+pKrm48cBEGUxREiUjN7v5RGgJH+DB5nKkV4nH3P7mvWV+mkDcAXZPhDprplFl1Q7YV56OyjAY+dlpY6xyGopDz9DmmZifqLxR6mP9eSCIeIM9VsDJUwhfnnwyxRuuzZWFa+Adu8kuaBR8RqjcdE=
